Traceback (most recent call last):
  File "/data/healthy-ml/scratch/odahleh/anaconda3/envs/icrm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/healthy-ml/scratch/odahleh/anaconda3/envs/icrm/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/healthy-ml/scratch/odahleh/mimic-mil/main.py", line 143, in <module>
    dataset = getattr(dataset_file, args.dataset)(args.data_dir, args.test_envs, hparams)
  File "/data/healthy-ml/scratch/odahleh/mimic-mil/dataset.py", line 102, in __init__
    clients, _ , self.data = utils.read_dir(self.root_dir)
  File "/data/healthy-ml/scratch/odahleh/mimic-mil/utils.py", line 414, in read_dir
    files = os.listdir(data_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'data/femnist-data/train'
